[tool.pylint.master]
good-names = [
  "Run",
  "_",
  "e",
  "ex",
  "i",
  "j",
  "k",
  "to",
]

[tool.pylint.messages_control]
disable = [
  "bad-whitespace",
  "bad-continuation",
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "too-few-public-methods",
]

[tool.pylint.format]
max-line-length = "88"
